#!/bin/bash
echo "cloning uro_pred_backend repos from github"
git clone -b main git@github.com:fianfian237/uro_pred_backend.git uro_pred_backend

echo "cloning uro_pred_frontend repos from github"
git clone -b main git@github.com:fianfian237/uro_pred_frontend.git uro_pred_frontend

echo "killing old docker processes"
sudo docker-compose rm -fs

echo "building docker containers"
sudo docker-compose up --build -d